/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonTable: typeof import('./src/components/CommonTable.vue')['default']
    CoTable: typeof import('./src/components/table/CoTable.vue')['default']
    CoTableOperation: typeof import('./src/components/table/CoTableOperation.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
